version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/opt
    links:
      - mongo
  mongo:
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
  mongo-express:
    restart: always
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://{MONGO_ROOT_USER}:{MONGOEXPRESS_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
    ports:
      - "8888:8081"

volumes:
  mongo-data:
  mongo-configdb: